#!/bin/sh
# $Id$
##
##  This file is part of the pyFormex project.
##  pyFormex is a tool for generating, manipulating and transforming 3D
##  geometrical models by sequences of mathematical operations.
##  Home page: http://pyformex.org
##  Project page:  https://savannah.nongnu.org/projects/pyformex/
##  Copyright (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##  Distributed under the GNU General Public License version 3 or later.
##
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see http://www.gnu.org/licenses/.
##
#
usage() {
  echo "$(basename $0) files..."
  echo "Adds the svn:keywords Id property to the specified files"
  echo "This will make subversion expand the \$Id\$ keyword on checkin."
  echo "Contributors should set this property to all newly added source files."
  echo "If you have properly set your subversion configuration, you will not"
  echo "have to do this explicitely for .py or .c files"
}

[ -n "$1" ] || { usage; exit; }

svn ps svn:keywords Id $@
