#!/bin/sh
#
# Create a pyFormex revision graph
#
URL=$(svn info | grep 'URL:' | sed 's|.*//||;s|.*@||')

[ "$URL" = "svn.berlios.de/svnroot/repos/pyformex/trunk" ] || {
    echo "URL: $URL"
    echo "This script should be executed in the pyformex checkout directory"
    exit
}

REV=$(svn info | gawk '/Revision:/{print $2}')
RECREV=$(head -n 1 pyformex.revisions | sed 's| .*||')

[ "$RECREV" = "$REV" ] || {
  echo "Creating new revision list: this may take some time"
  svn log | gawk '/^r[0-9]+/{ sub("r","",$1); print $1, $5}' > pyformex.revisions
}

gnuplot pyformex-rev.gnu
