#!/bin/sh
#
# This script helps with installing the gts library and utilities from source:
#
# ./install_gts get unpack make
# sudo ./install_gts install rename
# ./install_gts clean
#
# Use at your own risk if you do not understand what is happening!
#

VERSION=0.7.6
NAME=gts-$VERSION
ARCHIVE=$NAME.tar.gz
URI=http://prdownloads.sourceforge.net/gts/$ARCHIVE

examples="cartesian cleanup coarsen delaunay gtstoc iso merge oocs optimize partition refine set smooth sphere split stripe transform traverse volume"

get() {
  wget $URI
}

unpack() {
  tar xvzf $ARCHIVE
}

Make() {
  cd $NAME
  ./configure
  make
}

install() {
  [ "$EUID" == "0" ] || {
      echo "install should be done as root!"
      return
  }
  cd $NAME
  DESTDIR=. make install 
}

rename() {
  [ "$EUID" == "0" ] || {
      echo "install should be done as root!"
      return
  }
  for name in $examples; do
      gtsname=gts${name#gts}
      src=/usr/local/bin/$name
      tgt=/usr/local/bin/$gtsname
      mv $src $tgt
  done
}

clean() {
    rm -rf $NAME
}

for cmd in "$@"; do

    case $cmd in 
	get | unpack | install | rename | clean ) $cmd;;
	make ) Make;;
        * ) echo "UNKNOWN command $cmd";;
    esac

done
