#!/bin/bash
##
##  This file is part of the pyFormex project.
##  pyFormex is a tool for generating, manipulating and transforming 3D
##  geometrical models by sequences of mathematical operations.
##  Home page: http://pyformex.org
##  Project page:  https://savannah.nongnu.org/projects/pyformex/
##  Copyright (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##  Distributed under the GNU General Public License version 3 or later.
##
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see http://www.gnu.org/licenses/.
##
#
# Install a pyformex svn version in the desktop menu
#

svndir=$(dirname $0)
cd $svndir
svndir=$(pwd)

if [ -n "$(type -P xdg-desktop-menu)" ]; then
    # Create the icon
    convert pyformex/icons/pyformex-64x64.png -pointsize 20 -style normal -weight bold -fill navy -gravity southeast -draw "text 0,0 \"SVN\"" pyformex-svn.png

    # Create the .desktop file
    sed "s|^Exec=.*|Exec=$svndir/pyformex/pyformex --redirect|;s|^Icon=.*|Icon=$svndir/pyformex-svn.png|;s|^Name=.*|Name=pyFormex (SVN)|" pyformex.desktop > pyformex-pyformex-svn.desktop

    # Install the .desktop file on xdg compliant systems
    xdg-icon-resource install --size 64 pyformex-svn.png
    xdg-desktop-icon install pyformex-svn.desktop
    xdg-desktop-menu install pyformex-svn.desktop

else
    echo "I can not install a desktop link because your system is not xdg compliant"
fi

