#!/bin/bash
# Create the index.html for the python docs
#

cd doc/html
{
  cat ../htmlindex.header
  for f in *.html; do
    echo "<li><a href=\"$f\">$f</a></li>"
  done
  cat ../htmlindex.footer
} > index.html
