#!/bin/sh
##
## This file is part of pyFormex 0.7 Release Fri Apr  4 18:41:11 2008
## pyFormex is a Python implementation of Formex algebra
## Website: http://pyformex.berlios.de/
## Copyright (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##
## This program is distributed under the GNU General Public License
## version 2 or later (see file COPYING for details)
##
#
# This is the pyformex post install script
#

instdir=$(pyformex --whereami | grep '^Script' | sed 's|.* ||')
echo "Executables installed in $instdir"
[ -d "$instdir" ] && install -m 0755 pyformex/lib/postabq $instdir

# install the .desktop file on xdg compliant systems

[ -n "$(type -P xdg-desktop-menu)" ] && {
    xdg-icon-resource install --size 64 pyformex/icons/pyformex-64x64.png
    xdg-desktop-icon install pyformex-pyformex.desktop
    xdg-desktop-menu install pyformex-pyformex.desktop
}

echo "Post-install done"
