#!/bin/bash
# $Id$
##
##  This file is part of pyFormex 0.8.5  (Sun Dec  4 21:24:46 CET 2011)
##  pyFormex is a tool for generating, manipulating and transforming 3D
##  geometrical models by sequences of mathematical operations.
##  Home page: http://pyformex.org
##  Project page:  http://savannah.nongnu.org/projects/pyformex/
##  Copyright 2004-2011 (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##  Distributed under the GNU General Public License version 3 or later.
##
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see http://www.gnu.org/licenses/.
##
#
echo "pyFormex pre-install script"
# receives build_base and install_lib as arguments
builddir=$1
instdir=$2
[ -z "$builddir" ] && builddir=build

error_exit() {
  echo "$1"
  exit 1
}

[ -d "$builddir" ] || error_exit "Could not find build directory: $builddir"

scriptdirs=$(ls -d $builddir/scripts*)

# Set the pyformex path in the search script in $1
fix_script() {
    script=$1/pyformex-search
    [ -f "$script" ] && {
	echo "  Fixing $script"
	sed -i "s|^pyformexdir=|pyformexdir=$instdir|" $script
    }
}

for d in ${scriptdirs}; do
    fix_script $d
done

echo "Pre-install done"

# End
