#!/bin/bash
# Tag the current repository
#
[ -n "$1" ] || {
	echo "Usage: TAG <release>"
    echo "  Tags the current repository as <release>"
    exit 1
}
RELEASE=$1
echo "Tag current repository as release $RELEASE? (y/n) "
read ans
if [ "${ans}" = "y" ]; then
	svn copy svn+ssh://svn.berlios.de/svnroot/repos/pyformex/trunk svn+ssh://svn.berlios.de/svnroot/repos/pyformex/tags/release-$RELEASE -m "Tagging the $RELEASE release of the 'pyFormex' project."
fi
