#!/bin/sh
# Zoek een string in all .py files
#
#set -f
files="*.py gui/*.py plugins/*.py examples/*.py"
for d in local stent; do
	[ -d "$d" ] && files="$files $d/*.py"
done
#echo "$files"
#set +f
#echo $files
 
fgrep "$1" $files
