#!/bin/sh
# Zoek een string in all .py files
#
#set -f
files="pyformex/*.py pyformex/gui/*.py pyformex/plugins/*.py pyformex/examples/*.py"
for d in local stent; do
	[ -d "$d" ] && files="$files $d/*.py"
done
#echo "$files"
#set +f
#echo $files
 
fgrep "$1" $files
