.. Links (URLs) for inclusion on the website pages   -*- rst -*-
  

.. _`development`: http://pyformex.berlios.de
.. _`Official releases`: http://developer.berlios.de/project/showfiles.php?group_id=2717
.. _`SVN repository`: http://developer.berlios.de/svn/?group_id=2717
.. _`FTP site`: ftp://ftp.berlios.de/pub/pyformex
.. _`latest`: ftp://ftp.berlios.de/pub/pyformex/pyformex-latest.tar.gz
  
.. _`Summary`: http://developer.berlios.de/projects/pyformex/
.. _`Forums`: http://developer.berlios.de/forum/?group_id=2717
.. _`Bug tracker`: http://developer.berlios.de/bugs/?group_id=2717

.. _`Online manual`: http://pyformex.berlios.de/manual/index.html
.. _`pydoc`: http://pyformex.berlios.de/doc/index.html
.. _`PDF-version`: ftp://ftp.berlios.de/pub/pyformex/pyformex.pdf


.. _`local FTP server`: ftp://bumps.ugent.be/pub/pyformex
.. _`BuMPix Linux Live`: ftp://bumps.ugent.be/pub/bumpix
.. _`Calpy`: ftp://bumps.ugent.be/pub/calpy

  
.. _`Python`: http://www.python.org
.. _`NumPy`: http://numpy.scipy.org
.. _`PyOpenGL`: http://pyopengl.sourceforge.net
.. _`Qt4`: http://trolltech.com/products/qt
.. _`PyQt4`: http://www.riverbankcomputing.co.uk/pyqt
.. _`GNU General Public License`: http://www.gnu.org/licenses/gpl.html


.. _`stent research group`: http://www.stent-ibitech.ugent.be
.. _`IBiTech - Ghent University`: http://www.ibitech.ugent.be
.. _`BuMPer cluster`: http://bumps.ugent.be/bumper
  
.. _`Bifurcation stenting`: http://www.stent-ibitech.ugent.be/downloads/Peter_Mortier_posterEBR2008.pdf
.. _`FE modeling of stents`: http://www.stent-ibitech.ugent.be/downloads/Poster_Peter_Mortier_NationalDay2007.pdf

.. End