// Script generated by pyFormex 0.9.0~a1 (0.8.9r5-218-gd021f70)

window.onload = function() {
var r = new X.renderer3D();
r.init();

var m0 = new X.mesh();
m0.file = 'BridgeDeck_m0.stl';
m0.color = [1.0, 0.0, 0.0];
r.add(m0);

var m1 = new X.mesh();
m1.file = 'BridgeDeck_m1.stl';
m1.color = [0.0, 0.0, 0.0];
r.add(m1);

var m2 = new X.mesh();
m2.file = 'BridgeDeck_m2.stl';
m2.color = [0.49803922, 0.49803922, 0.49803922];
r.add(m2);

var m3 = new X.mesh();
m3.file = 'BridgeDeck_m3.stl';
m3.color = [0.93333334, 0.0, 0.0];
r.add(m3);

var m4 = new X.mesh();
m4.file = 'BridgeDeck_m4.stl';
m4.color = [0.2, 0.2, 0.2];
r.add(m4);

var m5 = new X.mesh();
m5.file = 'BridgeDeck_m5.stl';
m5.color = [0.80392158, 0.0, 0.0];
r.add(m5);

var m6 = new X.mesh();
m6.file = 'BridgeDeck_m6.stl';
m6.color = [1.0, 1.0, 1.0];
r.add(m6);

var m7 = new X.mesh();
m7.file = 'BridgeDeck_m7.stl';
m7.color = [1.0, 0.0, 0.0];
r.add(m7);

var m8 = new X.mesh();
m8.file = 'BridgeDeck_m8.stl';
m8.color = [0.80392158, 0.36078432, 0.36078432];
r.add(m8);

var m9 = new X.mesh();
m9.file = 'BridgeDeck_m9.stl';
m9.color = [1.0, 0.3882353, 0.27843139];
r.add(m9);

r.onShowtime = function() {
var gui = new dat.GUI();
var gui_m0 = gui.addFolder('m0');
var gui_m0_opacity = gui_m0.add(m0,'opacity',0,1);
var gui_m0_visible = gui_m0.add(m0,'visible');
var gui_m0_color = gui_m0.addColor(m0,'color');
var gui_m1 = gui.addFolder('m1');
var gui_m1_opacity = gui_m1.add(m1,'opacity',0,1);
var gui_m1_visible = gui_m1.add(m1,'visible');
var gui_m1_color = gui_m1.addColor(m1,'color');
var gui_m2 = gui.addFolder('m2');
var gui_m2_opacity = gui_m2.add(m2,'opacity',0,1);
var gui_m2_visible = gui_m2.add(m2,'visible');
var gui_m2_color = gui_m2.addColor(m2,'color');
var gui_m3 = gui.addFolder('m3');
var gui_m3_opacity = gui_m3.add(m3,'opacity',0,1);
var gui_m3_visible = gui_m3.add(m3,'visible');
var gui_m3_color = gui_m3.addColor(m3,'color');
var gui_m4 = gui.addFolder('m4');
var gui_m4_opacity = gui_m4.add(m4,'opacity',0,1);
var gui_m4_visible = gui_m4.add(m4,'visible');
var gui_m4_color = gui_m4.addColor(m4,'color');
var gui_m5 = gui.addFolder('m5');
var gui_m5_opacity = gui_m5.add(m5,'opacity',0,1);
var gui_m5_visible = gui_m5.add(m5,'visible');
var gui_m5_color = gui_m5.addColor(m5,'color');
var gui_m6 = gui.addFolder('m6');
var gui_m6_opacity = gui_m6.add(m6,'opacity',0,1);
var gui_m6_visible = gui_m6.add(m6,'visible');
var gui_m6_color = gui_m6.addColor(m6,'color');
var gui_m7 = gui.addFolder('m7');
var gui_m7_opacity = gui_m7.add(m7,'opacity',0,1);
var gui_m7_visible = gui_m7.add(m7,'visible');
var gui_m7_color = gui_m7.addColor(m7,'color');
var gui_m8 = gui.addFolder('m8');
var gui_m8_opacity = gui_m8.add(m8,'opacity',0,1);
var gui_m8_visible = gui_m8.add(m8,'visible');
var gui_m8_color = gui_m8.addColor(m8,'color');
var gui_m9 = gui.addFolder('m9');
var gui_m9_opacity = gui_m9.add(m9,'opacity',0,1);
var gui_m9_visible = gui_m9.add(m9,'visible');
var gui_m9_color = gui_m9.addColor(m9,'color');

var gui_camera = gui.addFolder('Camera');
var gui_camera_reset = gui_camera.add(r.camera,'reset');
}

r.camera.position = [-57.125452558349309, 4.9935401340596126, 18.241887876443158];
r.camera.focus = [0.0, 0.0, 0.0];
r.camera.up = [0.080655418, 0.99653518, -0.020215292];

r.render();
};
