#!/usr/bin/env python
##
##  This file is part of pyFormex 0.8.5  (Sun Dec  4 21:24:46 CET 2011)
##  pyFormex is a tool for generating, manipulating and transforming 3D
##  geometrical models by sequences of mathematical operations.
##  Home page: http://pyformex.org
##  Project page:  http://savannah.nongnu.org/projects/pyformex/
##  Copyright 2004-2011 (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##  Distributed under the GNU General Public License version 3 or later.
##
##
##  This program is free software: you can redistribute it and/or modify
##  it under the terms of the GNU General Public License as published by
##  the Free Software Foundation, either version 3 of the License, or
##  (at your option) any later version.
##
##  This program is distributed in the hope that it will be useful,
##  but WITHOUT ANY WARRANTY; without even the implied warranty of
##  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
##  GNU General Public License for more details.
##
##  You should have received a copy of the GNU General Public License
##  along with this program.  If not, see http://www.gnu.org/licenses/.
##
#

import os,sys,commands


def find_Python_headers():
    """Find the path to the Python.h header file."""
    python_include = sys.prefix+'/include/python'+sys.version[:3]
    if os.path.exists(os.path.join(python_include,'Python.h')):
        return python_include
    else:
        return ''


def find_Numpy_headers():
    """Find the path to the numpy/arrayobject.h header file."""
    from numpy.distutils.misc_util import get_numpy_include_dirs
    numpy_include = get_numpy_include_dirs()[0]
    if os.path.exists(os.path.join(numpy_include,'numpy','arrayobject.h')):
        return numpy_include
    else:
        return ''


if __name__ == "__main__":

    for a in sys.argv[1:]:

        if a == '-P':
            print find_Python_headers()
        elif a == '-N':
            print find_Numpy_headers()
