#!/usr/bin/env pyformex
# $Id$

from plugins import f2abq, stl, tetgen, stl_abq
import commands, os


def stl_import(fn):
    """Read and display an stl model from ascii file fn.
    
    Returns the model in a Formex.
    """
    message("Processing file %s" % fn)
    F = Formex(stl.read_ascii(fn))
    draw(F,color='green')
    message("There are %d triangles in the model" % F.f.shape[0])
    message("The bounding box is\n%s" % F.bbox())
    return F


def stl_export(fn,F,header="Created by stl_examples.py"):
    """Export an stl model stored in Formex F in Abaqus .inp format."""
    message("Creating nodes and elements. This may take some time!")
    GD.app.processEvents()
    nodes,elems = F.nodesAndElements()
    nnodes = nodes.shape[0]
    nelems = elems.shape[0]
    message("There are %d unique nodes and %d triangle elements in the model." % (nnodes,nelems))
    abq_export(fn,nodes,elems,'S3',header)



def stl_tetgen(fn):
    """Generate a volume tetraeder mesh inside an stl surface."""
    sta,out = commands.getstatusoutput('tetgen %s' % fn)
    message(out)


def read_tetgen(fn):
    """Read a tetgen model from files  fn.node, fn.ele, fn.smesh."""
    nodes = tetgen.readNodes(f+'.node')
    print "Read %d nodes" % nodes.shape[0]
    elems = readElems(f+'.ele')
    print "Read %d tetraeders" % elems.shape[0]
    surf = readSurface(f+'.smesh')
    print "Read %d triangles" % elems.shape[0]
    return nodes,elems,surf
 
# Processing starts here
    
os.chdir('/home/bene/prj/pyformex/stl')
message("Your current workdir is %s" % os.getcwd())

message("Choose the input .stl file\nIf you have none, run the Sphere_stl example to create one.")
fn = askFilename(".","Stl files (*.stl)")
if not fn:
    exit()
    
F = stl_import(fn)
bn = os.path.splitext(fn)[0]
    
if ack("Shall I export this in Abaqus .inp format (SLOW!)?"):
    stl_export(bn+'.inp',F,"Abaqus model converted from STL file %s" % fn)

if ack("Shall I create a tetraeder mesh inside the surface?"):
    stl_tetgen(fn)

if ack("Shall I read the generated mesh?"):
    nodes,elems,surf = read_tetgen(bn+'.1') # tetgen add extra '.1'
    volume = Formex(nodes[elems-1])
    surface = Formex(nodes[surf-1])
    clear()
    if ack("Shall I show the surface mesh (triangles)?"):
        draw(surface)
    if ack("Shall I show the volume mesh (tetraeders)?"):
        draw(volume,eltype='tet',color='random')

    if ack("Shall I export the surface mesh in Abaqus .inp format?"):
        stl_abq.abq_export(bn+'-surface.inp',nodes,surf,'S3',"Abaqus model generated by tetgen from surface in STL file %s" % fn)
    if ack("Shall I export the volume mesh in Abaqus .inp format?"):
        stl_abq.abq_export(bn+'volume.inp',nodes,elems,'C3D%d' % elems.shape[1],"Abaqus model generated by tetgen from surface in STL file %s" % fn)
    

# End
