#!/bin/sh
#
# List the images in the tex input files
#
# or check that the images exist (if -c as first parameter)
#

# what to do if -c option is given:
# check that images (.png and .eps) exist
check() {
  echo -n "$f: "
  [ -f images/$1.png -a -f images/$1.eps ] && { echo OK; return; }
  [ -f images/$1.png ] && echo "NO .png " 
  [ -f images/$1.eps ] && echo "NO .eps " 
}

dofunc=echo
[ "$1" = "-c" ] && {
  dofunc=check
  shift
}

files=$@
[ -z "$files" ] && files=*.tex
for f in $(fgrep includegraphics $files  | sed 's|.*images/||;s|}.*||'); do
  $dofunc $f
done

