.. $Id: defines.inc 1094 2009-09-02 10:08:12Z bverheg $

.. common definitions for pyFormex documentation 

.. |button-play| image:: images/next.png
.. |button-step| image:: images/step.png
.. |button-wireframe| image:: images/wireframe.png
.. |button-smooth| image:: images/smooth.png
.. |button-flat| image:: images/flat.png
.. |button-smoothwire| image:: images/smoothwire.png
.. |button-transparent| image:: images/transparent.png
.. |button-front| image:: images/front.png
.. |button-iso| image:: images/iso.png

