.. $Id: links.inc 2075 2011-11-14 10:16:40Z bverheg $  -*- rst -*- 
  
..
  This file is part of the pyFormex project.
  pyFormex is a tool for generating, manipulating and transforming 3D
  geometrical models by sequences of mathematical operations.
  Home page: http://pyformex.org
  Project page:  https://savannah.nongnu.org/projects/pyformex/
  Copyright (C) Benedict Verhegghe (benedict.verhegghe@ugent.be)
  Distributed under the GNU General Public License version 3 or later.
  
  
  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see http://www.gnu.org/licenses/.
  

.. _`email us`: mailto:benedict.verhegghe@ugent.be
.. _`pyFormex website`: http://pyformex.org
.. _`Home Page`: http://www.nongnu.org/pyformex/
.. _`Documentation`: http:///www.nongnu.org/pyformex/doc/

.. _`Online manual`: http:///www.nongnu.org/pyformex/doc/index.html
.. _`Introduction to pyFormex`: http:///www.nongnu.org/pyformex/doc/intro.html
.. _`Installing pyFormex`: http:///www.nongnu.org/pyformex/doc/install.html
.. _`pyFormex tutorial`: http:///www.nongnu.org/pyformex/doc/tutorial.html
.. _`pyFormex reference manual`: http:///www.nongnu.org/pyformex/doc/refman.html
.. _`pyFormex user guide`: http:///www.nongnu.org/pyformex/doc/user-guide.html
.. _`pyFormex examples`: http:///www.nongnu.org/pyformex/doc/examples.html
.. _`PDF version`: ftp://ftp.berlios.de/pub/pyformex/pyformex.pdf

.. _`Savannah`: http://savannah.nongnu.org/
.. _`Project page`: http://savannah.nongnu.org/projects/pyformex/
.. _`Support tracker`: http://savannah.nongnu.org/support/?group=pyformex
.. _`Bug tracker`: http://savannah.nongnu.org/bugs/?group=pyformex
.. _`Source code`: http://savannah.nongnu.org/svn/?group=pyformex
.. _`News`: http://savannah.nongnu.org/news/?group=pyformex
.. _`Releases`: http://download-mirror.savannah.gnu.org/releases/pyformex/

.. _`FTP site`: ftp://ftp.berlios.de/pub/pyformex
.. _`latest`: ftp://ftp.berlios.de/pub/pyformex/pyformex-latest.tar.gz

.. _`local FTP server`: ftp://bumps.ugent.be/pub/pyformex
.. _`latest BuMPix image`: ftp://bumps.ugent.be/pub/bumpix/bumpix-latest.img
.. _`BuMPix Live GNU/Linux`: ftp://bumps.ugent.be/pub/bumpix
.. _`Calpy`: ftp://bumps.ugent.be/pub/calpy

  
.. _`Python`: http://www.python.org
.. _`Python documentation`: http://www.python.org/doc
.. _`Python tutorial`: http://docs.python.org/tutorial
.. _`NumPy`: http://numpy.scipy.org
.. _`PyOpenGL`: http://pyopengl.sourceforge.net
.. _`Qt4`: http://trolltech.com/products/qt
.. _`PyQt4`: http://www.riverbankcomputing.co.uk/pyqt
.. _`Subversion`: http://subversion.tigris.org
.. _`Sphinx`: http://sphinx.pocoo.org
.. _`reStructuredText`: http://docutils.sourceforge.net/rst.html
.. _`GIMP`: http://www.gimp.org

.. _`GNU GPL`: http://www.gnu.org/licenses/gpl.html
.. _`GNU General Public License`: http://www.gnu.org/licenses/gpl.html
.. _`Free Software Foundation`: http://fsf.org
.. _`Debian GNU/Linux`: http://www.debian.org
.. _`Debian Live Wiki`: http://wiki.debian.org/DebianLive/Howto/USB

.. _`dd for Windows`: http://www.chrysocome.net/dd

.. _`stent research group`: http://www.stent-ibitech.ugent.be
.. _`IBiTech-bioMMeda`: http://www.biommeda.ugent.be
.. _`IBiTech, Ghent University`: http://www.ibitech.ugent.be
.. _`BuMPer cluster`: http://bumps.ugent.be/bumper
.. _`FEops`: http://www.feops.com  

.. _`Vascular Modeling Toolkit`: http://www.vmtk.org

.. End
