#!/usr/bin/env python
# $Id$
##
## This file is part of pyFormex 0.7.2 Release Tue Sep 23 16:18:43 2008
## pyFormex is a Python implementation of Formex algebra
## Website: http://pyformex.berlios.de/
## Copyright (C) Benedict Verhegghe (benedict.verhegghe@ugent.be) 
##
## This program is distributed under the GNU General Public License
## version 2 or later (see file COPYING for details)
##
"""Display help"""

import pyformex as GD

import os,sys
import draw
import utils
import tempfile
import random
import viewport
from gettext import gettext as _

def help(page=None):
    """Display a html help page.

    If no page is specified, the help manual is displayed.

    If page is a string starting with 'http:', the page is displayed with
    the command set in GD.cfg['browser'], else with the command in
    GD.cfg['viewer']
    """
    if not page:
        page = GD.cfg['help/manual']
    if page.startswith('http:'):
        browser = GD.cfg['browser']
    else:
        browser = GD.cfg['viewer']
    pid = utils.spawn(' '.join([browser,page]))


def catchAndDisplay(cmd):
    """Catch stdout from a Python cmd and display it in a window."""
    save = sys.stdout
    try:
        f = tempfile.TemporaryFile('w+')
        sys.stdout = f
        eval(cmd)
        f.seek(0)
        draw.showText(f.read())
    finally:
        sys.stdout = save
        

def cmdline():
    """Display the pyFormex command line help."""
    catchAndDisplay('GD.print_help()')

def manual():
    """Display the pyFormex manual."""
    help(GD.cfg['help/manual'])

def pydoc():
    """Display the pydoc information."""
    help(GD.cfg['help/pydocs'])

def website():
    """Display the pyFormex website."""
    help(GD.cfg['help/website'])

def webman():
    """Display the pyFormex website."""
    help(GD.cfg['help/webmanual'])

def readme():
    """Display the pyFormex description."""
    draw.showText(file(GD.cfg['help/readme']).read())

def license():
    """Display the pyFormex description."""
    draw.showText(file(GD.cfg['help/license']).read())

def opengl():
    """Display the OpenGL format description."""
    draw.showText(viewport.OpenGLFormat())

def detected():
    """Display the detected software components."""
    utils.checkExternal()
    catchAndDisplay('utils.printDetected()')

def about():
    """Display short information about pyFormex."""
    draw.showInfo("""%s

A tool for generating and operating on large 3D structures by mathematical transfomations.

Copyright 2004-2008 Benedict Verhegghe.
Distributed under the GNU GPL v2 or higher.
""" % GD.Version)

def developers():
    """Display the list of developers."""
    draw.showInfo("""
This is an alphabetic list of the
major contributors to pyFormex:

Matthieu De Beule
Gianluca De Santis
Bart Desloovere
Peter Mortier
Tim Neels
Sofie Van Cauter
Benedict Verhegghe

If you feel that your name was
left out in error, please contact us.
""")

                  
cookies = [
    "Smoking may be hazardous to your health.",
    "Windows is a virus.",
    "Coincidence does not exist. Perfection does.",
    "It's all in the code.",
    "Python is the universal glue.",
    ]    

random.shuffle(cookies)

def roll(l):
    l.append(l.pop(0))

def cookie():
    draw.showInfo(cookies[0],["OK"])
    roll(cookies)



MenuData = [
    (_('&Manual (local)'),manual),
    (_('&Manual (online)'),webman),
    (_('pyFormex &Website'),website),
#    (_('&PyDoc'),pydoc,dict(tooltip='Autogenerated documentation from the pyFormex sources')),
    ('---',None),
    (_('&Command line options'),cmdline),
    (_('&Readme'),readme), 
    (_('&License'),license), 
    (_('&Detected Software'),detected), 
    (_('&OpenGL Format'),opengl), 
    (_('&Fortune Cookie'),cookie),
    (_('&Developers'),developers), 
    (_('&About'),about), 
    ]

# End
