#!/bin/sh
#
#       Script to fetch our project HTML
#
umask 002
#
# Get the summary
#
/usr/bin/wget -q -O ~/projhtml.cache 'http://developer.berlios.de/export/projhtml.php?group_id=2717&mode="compact"&no_table="1"'  > /dev/null
/bin/cp -f ~/projhtml.cache /home/groups/pyformex/htdocs/projhtml.cache
#
# Get the news
#
/usr/bin/wget -q -O ~/projnews.cache 'http://developer.berlios.de/export/projnews.php?group_id=2717&limit="4"&flat="1"&show_summaries="1"'  > /dev/null
/bin/cp -f ~/projnews.cache /home/groups/pyformex/htdocs/projnews.cache
