<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

<head>
<title>pyFormex</title>
<link rel="stylesheet" href="pyformex.css" type="text/css" />
<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
<meta name="description" content="pyFormex - A tool for generating, manipulating and operating on large geometrical models of 3D structures by sequences of mathematical transformations" />
<meta name="keywords" content="geometries" />
</head>

<body>

<div id="page">

<div id="top1">
  <img src="images/scallop_dome_small.png" alt="scallop dome" border="0" hspace="20" vspace="12" align="left"/>
  <img src="images/pyformex_logo.png" alt="pyformex logo" border="0" hspace="10" vspace="12" align="left"/>
</div>

