#!/bin/bash
#
#  Script to create Debian packages
#
#

# source the version data
. ../RELEASE

PYFDIR=pyformex-$RELEASE
echo "Working on $PYFDIR"

if [ "$RELEASE" = "$VERSION" ]; then
    echo "This is an official release"
    SOURCE=../dist/pyformex/pyformex-$RELEASE.tar.gz
else
    echo "This is an interim release"
    SOURCE=../dist/pyformex-$RELEASE.tar.gz
fi
ORIG=pyformex_$RELEASE.orig.tar.gz

[ -f $PYFDIR/debian/changelog ] && PKGVER=$(expr "$(head -n 1 $PYFDIR/debian/changelog)" : '.*(\(.*\)).*')


unpack() {
    [ -d "$PYFDIR" ] && rm -rf $PYFDIR
    tar xf $SOURCE
    cp -a debian-template $PYFDIR/debian
    ln -sfn ${SOURCE} ${ORIG}
    # For now !!!
    #rm $PYFDIR/debian/*.doc-base
}


build() {
    pushd $PYFDIR
    debuild -us -uc
    popd
}


buildlib() {
    pushd $PYFDIR
    debuild -i -us -uc -B
    popd
}


install() {
    sudo debi pyformex_${PKGVER}_amd64.changes
}

pkglst() {
    debc pyformex_${PKGVER}_amd64.changes > pkglst
}

final() {
    pushd $PYFDIR
    debuild
    popd
}


upload() {
    PKGVER=$(expr "$(head -n 1 $PYFDIR/debian/changelog)" : '.*(\(.*\)).*')
    CHANGES=pyformex_${PKGVER}_amd64.changes
    echo Uploading ${CHANGES}
    [ -f "$CHANGES" ] && dput mentors $CHANGES
}


clean() {
    pushd $PYFDIR
    dh_clean
    popd
}


bump() {
    OLDPKGVER=$(expr "$(head -n 1 $PYFDIR/debian/changelog)" : '.*(\(.*\)).*')
    ARCHDIR=uploaded/${OLDPKGVER}
    mkdir $ARCHDIR && mv pyformex_${PKGVER}[_.]* $ARCHDIR
    pushd $PYFDIR
    dch -i
    PKGVER=$(expr "$(head -n 1 debian/changelog)" : '.*(\(.*\)).*')
    sed -i "s|pyformex(=$OLDPKGVER)|pyformex(=$PKGVER)|" debian/control
    popd
    cp $PYFDIR/debian/control $PYFDIR/debian/changelog debian-ex
}


for cmd in "$@"; do
    $cmd
done
